In [1]:
import numpy as np

In [2]:
x = np.array([[ 0,  1,  2],
              [ 3,  4,  5],
              [ 6,  7,  8],
              [ 9, 10, 11]])
rows = np.array([[0, 0],
                 [3, 3]], dtype=np.intp)
columns = np.array([[0, 2],
                    [0, 2]], dtype=np.intp)
x[rows, columns]

array([[ 0,  2],
       [ 9, 11]])

In [3]:
rows = [0, 2]
x[rows, :]

array([[0, 1, 2],
       [6, 7, 8]])

In [4]:
rows = np.array([0, 3], dtype=np.intp)
columns = np.array([0, 2], dtype=np.intp)
x[rows, columns]

array([ 0, 11])

In [5]:
rows = [0, 3]
columns = [0, 2]
x[rows, columns]

array([ 0, 11])

In [6]:
x[rows, [0, 1, 2, 3]]

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (2,) (4,) 

In [7]:
x[0:1, :]

array([[0, 1, 2]])

In [10]:
print(x[2,:].shape)

(3,)


In [19]:
sums = {
  "a": 999,
  "b": 121,
  "c": 333
}

avgs = {}
sums_list = sums.items()
for classname, summa in sums_list:
    avg = summa / 100.0
    avgs.update({classname: avg})
    
print(avgs)

{'a': 9.99, 'b': 1.21, 'c': 3.33}


In [20]:
import matplotlib.pyplot as plt

In [ ]:
# plot the histograms
fig_histos, ax_histos = plt.subplots(15,1)
# for each class, plot its average histogram
for classname, histo in avg_histos.items():
    vocab_indices = np.arange(0,vocab_size)
    assert vocab_indices.shape == histo.shape
    ax_histos[i].bar(vocab_indices, histo)
    ax_histos[i].title.set_text(f'Average histogram for scene: {classname}')
plt.show()

In [21]:
classes = ['a', 'b', 'c']
folder = 'b'
np.argwhere(np.core.defchararray.equal(classes, folder))

array([[1]])

In [24]:
num_classes = 3
feats = np.array([0, 2, 1])
print(feats)
feats_one_hot = np.zeros((feats.shape[0], num_classes))
feats_one_hot[range(0, feats.shape[0]), feats[range(0, feats.shape[0])]] = 1
print(feats_one_hot)

[0 2 1]
[[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]


In [28]:
feats_int = np.argmax(feats_one_hot, axis=1)
print(feats_int)

[0 2 1]
