In [2]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([True, False, True])
a[b] = -1
print(a)

[-1  2 -1]


In [11]:
a[a>=0]

array([2])

In [12]:
print(f"{7.3%3.6}")

0.09999999999999964


In [20]:
import math
math.degrees(-4*math.pi-0.05) % 360.0

357.13521102434584

In [20]:
c = np.array([1, 2, 3])
print(c[0:-1])
print(c[-1])

[1 2]
3


In [21]:
print(c[c<3])

[1 2]


In [8]:
c[c<3] = 0
print(c)

[0 0 3]


In [9]:
d = np.array([[1, 2], [3, 4], [5, 6]])
print(d)

[[1 2]
 [3 4]
 [5 6]]


In [10]:
dNew = np.append(d, np.ones((d.shape[0], 1), dtype=np.float64), axis=1)
print(dNew)

[[1. 2. 1.]
 [3. 4. 1.]
 [5. 6. 1.]]


In [11]:
e = np.array([1, 2, 3, 4, 5])
print(e.shape)

(5,)


In [16]:
eNew = np.expand_dims(e, axis=1)
print(eNew.shape)
eNew = np.repeat(eNew, 2, axis=1)
print(eNew)

(5, 1)
[[1 1]
 [2 2]
 [3 3]
 [4 4]
 [5 5]]


In [17]:
ind = np.array([0, 2, 4])
print(ind.shape)

(3,)


In [18]:
eNewSelected = eNew[ind, :]
print(eNewSelected)

[[1 1]
 [3 3]
 [5 5]]


In [25]:
f = np.array([[1, 2], [3, 4], [5, 6]])
fMask = np.array([1, 0, 1])
print(fMask>0)
fNew = f[fMask>0, :]
print(fNew)

[ True False  True]
[[1 2]
 [5 6]]
